---
# ============================================================================
# FILE: site.yml
# Main provisioning playbook - calls individual roles
# Each role is now self-contained (no common role)
# ============================================================================

- name: Provision macOS
  hosts: all
  become: false

  # ========================================================================
  # PRE-TASKS - Run before any roles
  # ========================================================================

  pre_tasks:
    - name: Check required network volumes are mounted
      include_tasks: "{{ playbook_dir }}/tasks/check_network_volumes.yml"
      vars:
        required_volumes: "{{ required_network_volumes }}"
      tags: ['always']

  # ========================================================================
  # ROLES - Each role is self-contained and handles its own:
  #   - Homebrew check/update
  #   - App installation (brew, mas, dmg)
  #   - SSH keys
  #   - Dotfiles
  #   - macOS baseline settings
  #   - macOS role-specific settings (if applicable)
  #   - Fonts
  # ========================================================================

  roles:
    - role: studio
      when: machine_type == 'studio'
      tags: ['studio']
      
    - role: laptop
      when: machine_type == 'laptop'
      tags: ['laptop']

    - role: editor
      when: machine_type == 'editor' 
      tags: ['editor']
      
    - role: family
      when: machine_type == 'family'
      tags: ['family']



  # ========================================================================
  # POST-TASKS - Run after all roles complete
  # These require all apps to be installed first
  # ========================================================================

  post_tasks:
    # ========================================================================
    # DOCK CONFIGURATION
    # ========================================================================
    
    - name: Configure Dock
      import_tasks: tasks/configure_dock.yml
      tags: ['dock', 'config']

    # ========================================================================
    # LOGIN ITEMS
    # ========================================================================
    
    - name: Configure login items
      import_tasks: tasks/configure_login_items.yml
      tags: ['login_items', 'config']

    # ========================================================================
    # APP SETTINGS RESTORATION
    # ========================================================================
    
    - name: Wait for apps to settle before restoring settings
      pause:
        seconds: 3
        prompt: "Allowing apps to finish installing..."
      when: 
        - restore_app_settings | default(true)
        - macos_network_base is defined
      tags: ['restore']

    - name: Check if app settings backup exists
      stat:
        path: "{{ macos_network_base }}/apps"
      register: app_backup_check
      when: 
        - restore_app_settings | default(true)
        - macos_network_base is defined
      tags: ['restore']
    
    - name: Load app backup definitions
      include_vars:
        file: "{{ playbook_dir }}/vars/app_backups.yml"
      when:
        - restore_app_settings | default(true)
        - macos_network_base is defined
      tags: ['restore']
    
    - name: Restore settings for installed apps only
      include_tasks: tasks/restore_app_if_exists.yml
      loop: "{{ lookup('vars', machine_type + '_apps_to_backup', default=[]) }}"
      loop_control:
        loop_var: app_key
        label: "{{ app_backup_definitions[app_key].name }}"
      vars:
        backup_base: "{{ macos_network_base }}/apps"
      when:
        - restore_app_settings | default(true)
        - app_backup_check.stat.exists | default(false)
        - macos_network_base is defined
        - not ansible_check_mode  
      tags: ['restore']

    # ========================================================================
    # COMPLETION MESSAGE
    # ========================================================================
    
    - name: Display completion message
      debug:
        msg: |
          ✅ Provisioning complete for {{ machine_type }} machine!
          
          {% if restore_app_settings | default(true) and macos_network_base is defined %}
          📦 Restored (for installed apps only):
            • SSH keys ({{ ssh_files | default([]) | length }} files)
            • Dotfiles ({{ lookup('vars', machine_type + '_dotfiles_files', default=dotfiles_files) | length }} files)
            • App settings
            • Fonts ({{ 'yes' if restore_fonts | default(true) else 'skipped' }})
          
          💡 For manually installed apps, restore settings with:
            ansible-playbook playbooks/restore-apps.yml -i inventory.ini --limit {{ machine_type }}
          
          Or restore specific apps:
            ansible-playbook playbooks/selective/restore-apps-selective.yml \
              -i inventory.ini --limit {{ machine_type }} \
              -e "apps_list=raycast,vscode"
          {% else %}
          💡 Settings were NOT restored. To restore them manually:
             ansible-playbook playbooks/restore-ssh.yml -i inventory.ini --limit {{ machine_type }}
             ansible-playbook playbooks/restore-dotfiles.yml -i inventory.ini --limit {{ machine_type }}
             ansible-playbook playbooks/restore-apps.yml -i inventory.ini --limit {{ machine_type }}
          {% endif %}
          
          ⚠️  IMPORTANT: Log out and back in for all settings to take effect
          
          📋 Quick reference:
            • Backup apps: ansible-playbook playbooks/backup-apps.yml -i inventory.ini --limit {{ machine_type }}
            • Backup SSH: ansible-playbook playbooks/backup-ssh.yml -i inventory.ini --limit {{ machine_type }}
            • List tags: ansible-playbook site.yml -i inventory.ini --limit {{ machine_type }} --list-tags
      tags: ['always']