---
- name: Provision macOS
  hosts: all
  become: false
  
  pre_tasks:
    - name: Check required network volumes are mounted
      include_tasks: "{{ playbook_dir }}/tasks/check_network_volumes.yml"
      vars:
        required_volumes:
          - backup_proxmox
      when: machine_type in ['video', 'personal']
      tags: ['always']

  roles:
    - role: common
      tags: ['common', 'apps']
      
    - role: video
      when: machine_type in ['video', 'personal']
      tags: ['video', 'apps']
      
    - role: personal
      when: machine_type == 'personal'
      tags: ['personal', 'apps']
      
    - role: family
      when: machine_type == 'family'
      tags: ['family', 'apps']

  post_tasks:
    - name: Configure Dock (after all apps installed)
      import_tasks: roles/common/tasks/dock.yml
      tags: ['dock', 'config']