---
- name: Provision macOS
  hosts: all
  become: false
  
  roles:
    - role: common
      tags: common
      
    - role: video
      when: "'video' in group_names"
      tags: video
      
    - role: personal
      when: "'personal' in group_names"
      tags: personal
      
    - role: family
      when: "'family' in group_names"
      tags: family