---
- name: Provision macOS
  hosts: all
  become: false
  
  pre_tasks:
    - name: Check required network volumes are mounted
      include_tasks: "{{ playbook_dir }}/tasks/check_network_volumes.yml"
      vars:
        required_volumes:
          - backup_proxmox
      when: machine_type in ['video', 'personal']
      tags: ['always']

  roles:
    - role: common
      tags: ['common', 'apps']
      
    - role: video
      when: machine_type in ['video', 'personal']
      tags: ['video', 'apps']
      
    - role: personal
      when: machine_type == 'personal'
      tags: ['personal', 'apps']
      
    - role: family
      when: machine_type == 'family'
      tags: ['family', 'apps']

  post_tasks:
    - name: Configure Dock (after all apps installed)
      import_tasks: roles/common/tasks/dock.yml
      tags: ['dock', 'config']
    
    # Wait for apps to settle before restoring settings
    - name: Wait for apps to settle
      pause:
        seconds: 3
        prompt: "Allowing apps to finish installing..."
      when: 
        - restore_app_settings | default(true)
        - macos_network_base is defined
      tags: ['restore', 'config']
    
    # Smart restore - only restore settings for apps that are actually installed
    - name: Check if app settings backup exists
      stat:
        path: "{{ macos_network_base }}/apps"
      register: app_backup_check
      when: 
        - restore_app_settings | default(true)
        - macos_network_base is defined
      tags: ['restore', 'config']
    
    - name: Load app backup definitions
      include_vars:
        file: "{{ playbook_dir }}/vars/app_backups.yml"
      when:
        - restore_app_settings | default(true)
        - macos_network_base is defined
      tags: ['restore', 'config']
    
    - name: Restore settings for installed apps
      include_tasks: tasks/restore_app_if_exists.yml
      loop: "{{ lookup('vars', machine_type + '_apps_to_backup', default=[]) }}"
      loop_control:
        loop_var: app_key
        label: "{{ app_backup_definitions[app_key].name }}"
      vars:
        backup_base: "{{ macos_network_base }}/apps"
      when:
        - restore_app_settings | default(true)
        - app_backup_check.stat.exists
        - macos_network_base is defined
      tags: ['restore', 'config']
    
    - name: Display completion message
      debug:
        msg: |
          ✅ Provisioning complete!
          
          {% if restore_app_settings | default(true) and macos_network_base is defined %}
          📦 Restored:
            • SSH keys ({{ ssh_files | default([]) | length }} files)
            • Dotfiles ({{ lookup('vars', machine_type + '_dotfiles_files', default=dotfiles_files) | length }} files)
            • App settings (for installed apps only)
          
          For manually installed apps, restore settings with:
            ansible-playbook playbooks/restore-apps.yml -i inventory.ini --limit {{ machine_type }}
          
          Or restore specific apps:
            ansible-playbook playbooks/selective/restore-apps-selective.yml \
              -i inventory.ini --limit {{ machine_type }} \
              -e "apps_list=raycast,vscode"
          {% else %}
          💡 Settings were NOT restored. To restore them:
             ansible-playbook playbooks/restore-ssh.yml -i inventory.ini --limit {{ machine_type }}
             ansible-playbook playbooks/restore-dotfiles.yml -i inventory.ini --limit {{ machine_type }}
             ansible-playbook playbooks/restore-apps.yml -i inventory.ini --limit {{ machine_type }}
          {% endif %}
          
          ⚠️  Remember to log out and back in for all settings to take effect
      tags: ['always']