---
- name: Provision macOS
  hosts: all
  become: false

  # ========================================================================
  # PRE-TASKS
  # ========================================================================

  pre_tasks:
    - name: Check required network volumes are mounted
      include_tasks: "{{ playbook_dir }}/tasks/check_network_volumes.yml"
      vars:
        required_volumes:
          - backup_proxmox
      when: machine_type in ['video', 'personal']
      tags: ['always']

  # ========================================================================
  # PROVISION ROLES
  # ========================================================================

  roles:
    - role: common
      tags: ['common', 'apps']
      
    - role: video
      when: machine_type in ['video', 'personal']
      tags: ['video', 'apps']
      
    - role: personal
      when: machine_type == 'personal'
      tags: ['personal', 'apps']
      
    - role: family
      when: machine_type == 'family'
      tags: ['family', 'apps']

  # ========================================================================
  # POST-TASKS
  # ========================================================================

  post_tasks:
    - name: Configure Dock (after all apps installed)
      import_tasks: roles/common/tasks/dock.yml
      tags: ['dock', 'config']

    - name: Configure login items (after all apps installed)
      import_tasks: roles/common/tasks/login_items.yml
      tags: ['login_items', 'config']
      when: configure_login_items | default(true)

    # Wait for apps to settle before restoring settings
    - name: Wait for apps to settle
      pause:
        seconds: 3
        prompt: "Allowing apps to finish installing..."
      when: 
        - restore_app_settings | default(true)
        - macos_network_base is defined
      tags: ['restore', 'config']

    # ========================================================================
    # FONTS: Restore BEFORE app settings
    # Apps like Terminal, VS Code, etc. may reference fonts in their prefs
    # ========================================================================

    - name: Check if fonts backup exists
      stat:
        path: "{{ macos_network_base }}/fonts"
      register: fonts_backup_check
      when: 
        - restore_fonts | default(true)
        - machine_type in ['personal', 'video']
        - macos_network_base is defined
      tags: ['fonts', 'restore', 'config']
    
    - name: Restore user fonts (before app settings)
      block:
        - name: Count fonts in backup
          find:
            paths: "{{ macos_network_base }}/fonts"
            patterns: "*.ttf,*.otf,*.ttc,*.dfont"
            recurse: yes
          register: backup_font_files
        
        - name: Display font restore info
          debug:
            msg: "📥 Restoring {{ backup_font_files.matched }} fonts from network backup (before app settings)"
        
        - name: Ensure user fonts directory exists
          file:
            path: "{{ ansible_facts['env']['HOME'] }}/Library/Fonts"
            state: directory
            mode: '0755'
        
        - name: Clear existing fonts
          shell: rm -rf "{{ ansible_facts['env']['HOME'] }}/Library/Fonts"/*
          args:
            warn: false
          changed_when: true
        
        - name: Restore fonts
          synchronize:
            src: "{{ macos_network_base }}/fonts/"
            dest: "{{ ansible_facts['env']['HOME'] }}/Library/Fonts/"
            recursive: yes
            delete: yes
            rsync_opts:
              - "--exclude=.DS_Store"
              - "--exclude=Thumbs.db"
          delegate_to: "{{ inventory_hostname }}"
        
        - name: Rebuild font cache
          shell: |
            atsutil databases -remove
            atsutil server -shutdown
            atsutil server -ping
          changed_when: false
          failed_when: false
        
        - name: Wait for font cache to rebuild
          pause:
            seconds: 2
            prompt: "Allowing font cache to rebuild..."
      when:
        - fonts_backup_check.stat.exists
        - backup_font_files.matched > 0
      tags: ['fonts', 'restore', 'config']

    # ========================================================================
    # APP SETTINGS
    # ========================================================================

    - name: Check if app settings backup exists
      stat:
        path: "{{ macos_network_base }}/apps"
      register: app_backup_check
      when: 
        - restore_app_settings | default(true)
        - macos_network_base is defined
      tags: ['restore', 'config']
    
    - name: Load app backup definitions
      include_vars:
        file: "{{ playbook_dir }}/vars/app_backups.yml"
      when:
        - restore_app_settings | default(true)
        - macos_network_base is defined
      tags: ['restore', 'config']
    
    - name: Restore settings for installed apps
      include_tasks: tasks/restore_app_if_exists.yml
      loop: "{{ lookup('vars', machine_type + '_apps_to_backup', default=[]) }}"
      loop_control:
        loop_var: app_key
        label: "{{ app_backup_definitions[app_key].name }}"
      vars:
        backup_base: "{{ macos_network_base }}/apps"
      when:
        - restore_app_settings | default(true)
        - app_backup_check.stat.exists
        - macos_network_base is defined
      tags: ['restore', 'config']

    # ========================================================================
    # NOTIFICATION
    # ========================================================================

    - name: Display completion message
      debug:
        msg: |
          ✅ Provisioning complete!
          
          {% if restore_app_settings | default(true) and macos_network_base is defined %}
          📦 Restored:
            • SSH keys ({{ ssh_files | default([]) | length }} files)
            • Dotfiles ({{ lookup('vars', machine_type + '_dotfiles_files', default=dotfiles_files) | length }} files)
            • App settings (for installed apps only)
          
          For manually installed apps, restore settings with:
            ansible-playbook playbooks/restore-apps.yml -i inventory.ini --limit {{ machine_type }}
          
          Or restore specific apps:
            ansible-playbook playbooks/selective/restore-apps-selective.yml \
              -i inventory.ini --limit {{ machine_type }} \
              -e "apps_list=raycast,vscode"
          {% else %}
          💡 Settings were NOT restored. To restore them:
             ansible-playbook playbooks/restore-ssh.yml -i inventory.ini --limit {{ machine_type }}
             ansible-playbook playbooks/restore-dotfiles.yml -i inventory.ini --limit {{ machine_type }}
             ansible-playbook playbooks/restore-apps.yml -i inventory.ini --limit {{ machine_type }}
          {% endif %}
          
          ⚠️  Remember to log out and back in for all settings to take effect
      tags: ['always']