---
- name: Provision macOS
  hosts: localhost
  become: false
  
  roles:
    - { role: common, tags: ['always'] }
    - { role: video, tags: ['video'] }
    - { role: family, tags: ['family'] }
    - { role: personal, tags: ['personal'] }